/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import javax.swing.JOptionPane;

public class JDlgJogos extends javax.swing.JDialog {

    /**
     * Creates new form JDlgUsuario
     */
    public JDlgJogos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        habilitar(false);
        setTitle("Cadastro Jogos");
    }

    private void habilitar(boolean status) {
        jTxtIdlfs_Cliente.setEnabled(status);
        jTxtLfs_nome_jogo.setEnabled(status);
        jCboLfs_classificacao_indicativa.setEnabled(status);
        jCboLfs_genero.setEnabled(status);
        jTxtLfs_preco.setEnabled(status);
        jTxtLfs_descricao.setEnabled(status);
        jFmtLfs_data_lancamento.setEnabled(status);
        jTxtLfs_estoque.setEnabled(status);
        jCboLfs_idioma.setEnabled(status);
        jFmtLfs_data_adicionado.setEnabled(status);
        jTxtLfs_desenvolvedora.setEnabled(status);
        jTxtLfs_avaliacao_media.setEnabled(status);
        jTxtLfs_modo_de_jogo.setEnabled(status);
        jCboLfs_plataforma.setEnabled(status);
        jChbLfs_status_disponibilidade.setEnabled(status);
        
        
        jBtnLfs_Incluir.setEnabled(!status);
        jBtnLfs_Alterar.setEnabled(!status);
        jBtnLfs_Excluir.setEnabled(!status);
        jBtnLfs_Pesquisar.setEnabled(!status);
        
        jBtnLfs_Confirmar.setEnabled(status);
        jBtnLfs_Cancelar.setEnabled(status);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTxtIdlfs_Cliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtLfs_nome_jogo = new javax.swing.JTextField();
        jCboLfs_classificacao_indicativa = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jCboLfs_genero = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTxtLfs_preco = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTxtLfs_descricao = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jFmtLfs_data_lancamento = new javax.swing.JFormattedTextField();
        jTxtLfs_estoque = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jCboLfs_idioma = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jFmtLfs_data_adicionado = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jTxtLfs_desenvolvedora = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTxtLfs_avaliacao_media = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTxtLfs_modo_de_jogo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jCboLfs_plataforma = new javax.swing.JComboBox<>();
        jChbLfs_status_disponibilidade = new javax.swing.JCheckBox();
        jBtnLfs_Incluir = new javax.swing.JButton();
        jBtnLfs_Cancelar = new javax.swing.JButton();
        jBtnLfs_Confirmar = new javax.swing.JButton();
        jBtnLfs_Excluir = new javax.swing.JButton();
        jBtnLfs_Pesquisar = new javax.swing.JButton();
        jBtnLfs_Alterar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("ID");

        jTxtIdlfs_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtIdlfs_ClienteActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome do Jogo");

        jCboLfs_classificacao_indicativa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+18", "+12", "Kids" }));
        jCboLfs_classificacao_indicativa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboLfs_classificacao_indicativaActionPerformed(evt);
            }
        });

        jLabel3.setText("Classificacao Idade");

        jCboLfs_genero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aventura", "RPG", "Terror", "Sobrevivencia" }));

        jLabel4.setText("Genero");

        jLabel5.setText("Preco");

        jLabel6.setText("Descricao");

        jLabel7.setText("Data Lancamento");

        jLabel8.setText("Estoque");

        jLabel9.setText("Idioma");

        jCboLfs_idioma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingles", "Portugues", "Espanhol" }));

        jLabel10.setText("Data Adicionado");

        jLabel11.setText("Desenvolvedora");

        jLabel12.setText("Avaliacao Media");

        jLabel13.setText("Modo de Jogo");

        jLabel14.setText("Plataforma");

        jCboLfs_plataforma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PC", "PS4", "PS3", "PS2", "Xbox" }));

        jChbLfs_status_disponibilidade.setText("Disponibilidade");

        jBtnLfs_Incluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluir.png"))); // NOI18N
        jBtnLfs_Incluir.setText("incluir");
        jBtnLfs_Incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLfs_IncluirActionPerformed(evt);
            }
        });

        jBtnLfs_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        jBtnLfs_Cancelar.setText("cancelar");
        jBtnLfs_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLfs_CancelarActionPerformed(evt);
            }
        });

        jBtnLfs_Confirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/confirmar.png"))); // NOI18N
        jBtnLfs_Confirmar.setText("confirmar");
        jBtnLfs_Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLfs_ConfirmarActionPerformed(evt);
            }
        });

        jBtnLfs_Excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/excluir.png"))); // NOI18N
        jBtnLfs_Excluir.setText("excluir");
        jBtnLfs_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLfs_ExcluirActionPerformed(evt);
            }
        });

        jBtnLfs_Pesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisar.png"))); // NOI18N
        jBtnLfs_Pesquisar.setText("pesquisar");
        jBtnLfs_Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLfs_PesquisarActionPerformed(evt);
            }
        });

        jBtnLfs_Alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        jBtnLfs_Alterar.setText("alterar");
        jBtnLfs_Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLfs_AlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jCboLfs_plataforma, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTxtLfs_preco, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtIdlfs_Cliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                                .addComponent(jLabel5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jFmtLfs_data_adicionado, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(209, 209, 209))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jTxtLfs_nome_jogo)
                                            .addGap(18, 18, 18)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(236, 236, 236)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCboLfs_classificacao_indicativa, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3))
                                        .addGap(31, 31, 31)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jCboLfs_genero, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(31, 31, 31)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTxtLfs_estoque, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jCboLfs_idioma, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel13)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel8)
                                                        .addGap(36, 36, 36)
                                                        .addComponent(jLabel9)))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(jTxtLfs_modo_de_jogo)))))
                            .addComponent(jChbLfs_status_disponibilidade)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTxtLfs_desenvolvedora, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                                        .addComponent(jTxtLfs_descricao, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFmtLfs_data_lancamento, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTxtLfs_avaliacao_media, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel12))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jBtnLfs_Incluir)
                        .addGap(30, 30, 30)
                        .addComponent(jBtnLfs_Alterar)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnLfs_Excluir)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnLfs_Confirmar)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnLfs_Cancelar)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnLfs_Pesquisar)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtIdlfs_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtLfs_nome_jogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCboLfs_classificacao_indicativa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCboLfs_genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtLfs_preco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtLfs_descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtLfs_data_lancamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtLfs_estoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCboLfs_idioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFmtLfs_data_adicionado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtLfs_desenvolvedora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtLfs_avaliacao_media, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtLfs_modo_de_jogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCboLfs_plataforma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jChbLfs_status_disponibilidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnLfs_Alterar)
                    .addComponent(jBtnLfs_Pesquisar)
                    .addComponent(jBtnLfs_Excluir)
                    .addComponent(jBtnLfs_Confirmar)
                    .addComponent(jBtnLfs_Cancelar)
                    .addComponent(jBtnLfs_Incluir))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtIdlfs_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtIdlfs_ClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtIdlfs_ClienteActionPerformed

    private void jBtnLfs_IncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLfs_IncluirActionPerformed
        // TODO add your handling code here:
        habilitar(true);
    }//GEN-LAST:event_jBtnLfs_IncluirActionPerformed

    private void jBtnLfs_AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLfs_AlterarActionPerformed
        // TODO add your handling code here:
        habilitar(true);
    }//GEN-LAST:event_jBtnLfs_AlterarActionPerformed

    private void jBtnLfs_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLfs_ExcluirActionPerformed
        // TODO add your handling code here:
        JOptionPane.showConfirmDialog(null, "Tem Certeza?");
    }//GEN-LAST:event_jBtnLfs_ExcluirActionPerformed

    private void jBtnLfs_ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLfs_ConfirmarActionPerformed
        // TODO add your handling code here:
        habilitar(false);
    }//GEN-LAST:event_jBtnLfs_ConfirmarActionPerformed

    private void jBtnLfs_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLfs_CancelarActionPerformed
        // TODO add your handling code here:
        habilitar(false);
    }//GEN-LAST:event_jBtnLfs_CancelarActionPerformed

    private void jBtnLfs_PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLfs_PesquisarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showInputDialog(null, "Entre com a chave primária");
    }//GEN-LAST:event_jBtnLfs_PesquisarActionPerformed

    private void jCboLfs_classificacao_indicativaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboLfs_classificacao_indicativaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboLfs_classificacao_indicativaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgJogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgJogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgJogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgJogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgJogos dialog = new JDlgJogos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnLfs_Alterar;
    private javax.swing.JButton jBtnLfs_Cancelar;
    private javax.swing.JButton jBtnLfs_Confirmar;
    private javax.swing.JButton jBtnLfs_Excluir;
    private javax.swing.JButton jBtnLfs_Incluir;
    private javax.swing.JButton jBtnLfs_Pesquisar;
    private javax.swing.JComboBox<String> jCboLfs_classificacao_indicativa;
    private javax.swing.JComboBox<String> jCboLfs_genero;
    private javax.swing.JComboBox<String> jCboLfs_idioma;
    private javax.swing.JComboBox<String> jCboLfs_plataforma;
    private javax.swing.JCheckBox jChbLfs_status_disponibilidade;
    private javax.swing.JFormattedTextField jFmtLfs_data_adicionado;
    private javax.swing.JFormattedTextField jFmtLfs_data_lancamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTxtIdlfs_Cliente;
    private javax.swing.JTextField jTxtLfs_avaliacao_media;
    private javax.swing.JTextField jTxtLfs_descricao;
    private javax.swing.JTextField jTxtLfs_desenvolvedora;
    private javax.swing.JTextField jTxtLfs_estoque;
    private javax.swing.JTextField jTxtLfs_modo_de_jogo;
    private javax.swing.JTextField jTxtLfs_nome_jogo;
    private javax.swing.JTextField jTxtLfs_preco;
    // End of variables declaration//GEN-END:variables
}
