/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import javax.swing.JOptionPane;

public class JDlgFornecedor extends javax.swing.JDialog {

    /**
     * Creates new form JDlgUsuario
     */
    public JDlgFornecedor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        habilitar(false);
        setTitle("Cadastro Fornecedor");
    }

    private void habilitar(boolean status) {
        jTxtIdlfs_Cliente.setEnabled(status);
        jTxtLfs_Razao_social.setEnabled(status);
        jFmtLfs_cnpj.setEnabled(status);
        jFmtLfs_Incricao_estadual.setEnabled(status);
        jFmtLfs_Celular.setEnabled(status);
        jTxtLfs_Endereco.setEnabled(status);
        jTxtLfs_Bairro.setEnabled(status);
        jTxtLfs_Cidade.setEnabled(status);
        jCbolfs_Estado.setEnabled(status);
        jTxtLfs_email.setEnabled(status);
        jFmtLfs_telefone.setEnabled(status);
        jFmtLfs_Cep.setEnabled(status);
        jTxtLfs_logradoro.setEnabled(status);
        jFmtLfs_dataCadastro.setEnabled(status);
        jTxtLfs_Numero.setEnabled(status);
        

        jBtnLfs_Incluir.setEnabled(!status);
        jBtnLfs_Alterar.setEnabled(!status);
        jBtnLfs_Excluir.setEnabled(!status);
        jBtnLfs_Pesquisar.setEnabled(!status);

        jBtnLfs_Confirmar.setEnabled(status);
        jBtnLfs_Cancelar.setEnabled(status);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTxtIdlfs_Cliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtLfs_Razao_social = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jFmtLfs_cnpj = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jFmtLfs_Celular = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jTxtLfs_Endereco = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTxtLfs_email = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jFmtLfs_telefone = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jFmtLfs_Cep = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        jTxtLfs_logradoro = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jFmtLfs_dataCadastro = new javax.swing.JFormattedTextField();
        jBtnLfs_Incluir = new javax.swing.JButton();
        jBtnLfs_Alterar = new javax.swing.JButton();
        jBtnLfs_Excluir = new javax.swing.JButton();
        jBtnLfs_Confirmar = new javax.swing.JButton();
        jBtnLfs_Cancelar = new javax.swing.JButton();
        jBtnLfs_Pesquisar = new javax.swing.JButton();
        jFmtLfs_Incricao_estadual = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTxtLfs_Numero = new javax.swing.JTextField();
        jCbolfs_Estado = new javax.swing.JComboBox<>();
        jTxtLfs_Bairro = new javax.swing.JTextField();
        jTxtLfs_Cidade = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("ID");

        jTxtIdlfs_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtIdlfs_ClienteActionPerformed(evt);
            }
        });

        jLabel2.setText("Razão Social");

        jTxtLfs_Razao_social.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtLfs_Razao_socialActionPerformed(evt);
            }
        });

        jLabel3.setText("Cnpj");

        jLabel4.setText("Incrição Estadual");

        jLabel6.setText("Bairro");

        jLabel7.setText("Celular");

        jLabel8.setText("Endereco");

        jLabel9.setText("Email");

        jLabel10.setText("Telefone");

        jFmtLfs_telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtLfs_telefoneActionPerformed(evt);
            }
        });

        jLabel11.setText("Estado");

        jLabel12.setText("Cep");

        jLabel14.setText("Logradoro");

        jTxtLfs_logradoro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtLfs_logradoroActionPerformed(evt);
            }
        });

        jLabel15.setText("Data Cadastro");

        jBtnLfs_Incluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluir.png"))); // NOI18N
        jBtnLfs_Incluir.setText("incluir");
        jBtnLfs_Incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLfs_IncluirActionPerformed(evt);
            }
        });

        jBtnLfs_Alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        jBtnLfs_Alterar.setText("alterar");
        jBtnLfs_Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLfs_AlterarActionPerformed(evt);
            }
        });

        jBtnLfs_Excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/excluir.png"))); // NOI18N
        jBtnLfs_Excluir.setText("excluir");
        jBtnLfs_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLfs_ExcluirActionPerformed(evt);
            }
        });

        jBtnLfs_Confirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/confirmar.png"))); // NOI18N
        jBtnLfs_Confirmar.setText("confirmar");
        jBtnLfs_Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLfs_ConfirmarActionPerformed(evt);
            }
        });

        jBtnLfs_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        jBtnLfs_Cancelar.setText("cancelar");
        jBtnLfs_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLfs_CancelarActionPerformed(evt);
            }
        });

        jBtnLfs_Pesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisar.png"))); // NOI18N
        jBtnLfs_Pesquisar.setText("pesquisar");
        jBtnLfs_Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLfs_PesquisarActionPerformed(evt);
            }
        });

        jFmtLfs_Incricao_estadual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtLfs_Incricao_estadualActionPerformed(evt);
            }
        });

        jLabel16.setText("Cidade");

        jLabel17.setText("Numero");

        jTxtLfs_Numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtLfs_NumeroActionPerformed(evt);
            }
        });

        jCbolfs_Estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MS", "PR", "SP", "MT" }));
        jCbolfs_Estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbolfs_EstadoActionPerformed(evt);
            }
        });

        jTxtLfs_Bairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtLfs_BairroActionPerformed(evt);
            }
        });

        jTxtLfs_Cidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtLfs_CidadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(91, 91, 91))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jTxtLfs_email)
                                    .addGap(30, 30, 30)))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jFmtLfs_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addGap(63, 63, 63))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jFmtLfs_dataCadastro)
                                    .addGap(75, 75, 75)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addGap(355, 355, 355))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jTxtLfs_logradoro)
                                    .addGap(272, 272, 272)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel17)
                                .addComponent(jTxtLfs_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jTxtIdlfs_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(67, 67, 67)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jTxtLfs_Razao_social, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTxtLfs_Bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(48, 48, 48)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTxtLfs_Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(59, 59, 59)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jCbolfs_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(93, 93, 93)
                                    .addComponent(jFmtLfs_Cep, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jFmtLfs_cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel7)
                                        .addComponent(jFmtLfs_Celular, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(74, 74, 74)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTxtLfs_Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel4)
                                        .addComponent(jFmtLfs_Incricao_estadual, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel12))))
                            .addContainerGap()))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jBtnLfs_Incluir)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnLfs_Alterar)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnLfs_Excluir)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnLfs_Confirmar)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnLfs_Cancelar)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnLfs_Pesquisar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtIdlfs_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtLfs_Razao_social, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtLfs_Incricao_estadual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtLfs_cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTxtLfs_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jFmtLfs_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jFmtLfs_Celular, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTxtLfs_Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtLfs_Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtLfs_Bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCbolfs_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jFmtLfs_Cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel17))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFmtLfs_dataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtLfs_logradoro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtLfs_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnLfs_Incluir)
                    .addComponent(jBtnLfs_Alterar)
                    .addComponent(jBtnLfs_Excluir)
                    .addComponent(jBtnLfs_Confirmar)
                    .addComponent(jBtnLfs_Cancelar)
                    .addComponent(jBtnLfs_Pesquisar))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtIdlfs_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtIdlfs_ClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtIdlfs_ClienteActionPerformed

    private void jTxtLfs_logradoroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtLfs_logradoroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtLfs_logradoroActionPerformed

    private void jBtnLfs_IncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLfs_IncluirActionPerformed
        // TODO add your handling code here:
        habilitar(true);
    }//GEN-LAST:event_jBtnLfs_IncluirActionPerformed

    private void jBtnLfs_AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLfs_AlterarActionPerformed
        // TODO add your handling code here:
        habilitar(true);
    }//GEN-LAST:event_jBtnLfs_AlterarActionPerformed

    private void jBtnLfs_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLfs_ExcluirActionPerformed
        // TODO add your handling code here:
        JOptionPane.showConfirmDialog(null, "Tem Certeza?");
    }//GEN-LAST:event_jBtnLfs_ExcluirActionPerformed

    private void jBtnLfs_ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLfs_ConfirmarActionPerformed
        // TODO add your handling code here:
        habilitar(false);
    }//GEN-LAST:event_jBtnLfs_ConfirmarActionPerformed

    private void jBtnLfs_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLfs_CancelarActionPerformed
        // TODO add your handling code here:
        habilitar(false);
    }//GEN-LAST:event_jBtnLfs_CancelarActionPerformed

    private void jBtnLfs_PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLfs_PesquisarActionPerformed
        // TODO add your handling code here:
       JOptionPane.showInputDialog(null, "Entre com a chave primária");
    }//GEN-LAST:event_jBtnLfs_PesquisarActionPerformed

    private void jFmtLfs_Incricao_estadualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtLfs_Incricao_estadualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtLfs_Incricao_estadualActionPerformed

    private void jFmtLfs_telefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtLfs_telefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtLfs_telefoneActionPerformed

    private void jTxtLfs_NumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtLfs_NumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtLfs_NumeroActionPerformed

    private void jCbolfs_EstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbolfs_EstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCbolfs_EstadoActionPerformed

    private void jTxtLfs_BairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtLfs_BairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtLfs_BairroActionPerformed

    private void jTxtLfs_CidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtLfs_CidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtLfs_CidadeActionPerformed

    private void jTxtLfs_Razao_socialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtLfs_Razao_socialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtLfs_Razao_socialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgFornecedor dialog = new JDlgFornecedor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnLfs_Alterar;
    private javax.swing.JButton jBtnLfs_Cancelar;
    private javax.swing.JButton jBtnLfs_Confirmar;
    private javax.swing.JButton jBtnLfs_Excluir;
    private javax.swing.JButton jBtnLfs_Incluir;
    private javax.swing.JButton jBtnLfs_Pesquisar;
    private javax.swing.JComboBox<String> jCbolfs_Estado;
    private javax.swing.JFormattedTextField jFmtLfs_Celular;
    private javax.swing.JFormattedTextField jFmtLfs_Cep;
    private javax.swing.JFormattedTextField jFmtLfs_Incricao_estadual;
    private javax.swing.JFormattedTextField jFmtLfs_cnpj;
    private javax.swing.JFormattedTextField jFmtLfs_dataCadastro;
    private javax.swing.JFormattedTextField jFmtLfs_telefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTxtIdlfs_Cliente;
    private javax.swing.JTextField jTxtLfs_Bairro;
    private javax.swing.JTextField jTxtLfs_Cidade;
    private javax.swing.JTextField jTxtLfs_Endereco;
    private javax.swing.JTextField jTxtLfs_Numero;
    private javax.swing.JTextField jTxtLfs_Razao_social;
    private javax.swing.JTextField jTxtLfs_email;
    private javax.swing.JTextField jTxtLfs_logradoro;
    // End of variables declaration//GEN-END:variables
}
